# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.github.carlo-colombo.mix-release"
version = "0.0.2"
name = "elixir mix release Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.github.carlo-colombo.elixir-builder"